name: 'release'

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    name: 'create release on master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: hub release create -m "this is custom run release" "$(date +%Y%m%d%H%M%S)"