name: 'release'

on:
  push:
    branches:
      - 'master'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:      

jobs:
  bump-version:
    name: 'create release on master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: v1.2.2
  build:
    name: 'build bundle and deploy'  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: 'build'
        run: npm i && npm run build
      - name: 'npm publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
      # - name: 'deploy surge'
      # - name: 'deploy github pages'
        