name: 'release'

on:
  push:
    branches:
      - 'master'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:      

jobs:
  bump-version:
    name: 'create release on master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}
      with:
        title: MyReleaseMessage